put-object became sync

diff --git a/S3/bash-scripts/sync b/S3/bash-scripts/sync
--- a/S3/bash-scripts/sync
+++ b/S3/bash-scripts/sync
@@ -1,1 +1,27 @@
 #!/usr/bin/env bash
+echo "== sync"
+# exit immediately if any command returns a non-zero status
+set -e
+
+# where we'll store the files
+OUTPUT_DIR="/tmp/S3/bash-scripts"
+
+# remove the folder if it already exists
+rm -r $OUTPUT_DIR
+
+# let's create the output folder
+mkdir -p $OUTPUT_DIR
+
+# generate a random number to determine
+# how many files to create
+NUM_FILES=$((RANDOM % 6 + 5))
+
+for ((i=1; i<=$NUM_FILES; i++)); do
+    # generate a random file name
+    RANDOM_FILENAME="$OUTPUT_DIR/file_$i.txt"
+
+    # generate random data and write it to the file
+    dd if=/dev/urandom of="$RANDOM_FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
+done
+
+tree $OUTPUT_DIR
